### ISSUE TITLE
Add black to the makefile

### ISSUE THREAD

**Issue by unbalancedparentheses** [lambdaclass/options_backtester#52]

**Comment by unbalancedparentheses** [comment]
@jrchatruc or @metdinov could you please check this?

**Comment by metdinov** [comment]
There is currently a `make lint` command that runs the linter and formatter.
Since black is currently en pre release, it is [difficult](https://github.com/microsoft/vscode-python/issues/5171) to get it working with pipenv.

We decided to go with [flake8](https://flake8.pycqa.org/en/latest/) for linting and [yapf](https://github.com/google/yapf) for formatting.
